export const ProductsData = [
  {
    id: 1,
    img: "https://ik.imagekit.io/aswathy/images/pizza1_Hek6UFiPN?updatedAt=1758276411591",
    alt: "pizza2",
    name: "Hawaiian ",
    desc: "Pizza sauce, mozzarella, ham, pineapple lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, quod. lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, quod.",
    price: "$9.99",
  },
  {
    id: 2,
    img: "https://ik.imagekit.io/aswathy/images/pizza1_Hek6UFiPN?updatedAt=1758276411591",
    alt: "pizza2",
    name: "Hawaiian ",
    desc: "Pizza sauce, mozzarella, ham, pineapple",
    price: "$9.99",
  },
  {
    id: 3,
    img: "https://ik.imagekit.io/aswathy/images/pizza1_Hek6UFiPN?updatedAt=1758276411591",
    alt: "pizza2",
    name: "Hawaiian ",
    desc: "Pizza sauce, mozzarella, ham, pineapple",
    price: "$9.99",
  },
  {
    id: 4,
    img: "https://ik.imagekit.io/aswathy/images/pizza1_Hek6UFiPN?updatedAt=1758276411591",
    alt: "pizza2",
    name: "Hawaiian ",
    desc: "Pizza sauce, mozzarella, ham, pineapple",
    price: "$9.99",
  },
  {
    id: 5,
    img: "https://ik.imagekit.io/aswathy/images/pizza1_Hek6UFiPN?updatedAt=1758276411591",
    alt: "pizza2",
    name: "Hawaiian ",
    desc: "Pizza sauce, mozzarella, ham, pineapple",
    price: "$9.99",
  },
  {
    id: 5,
    img: "https://ik.imagekit.io/aswathy/images/pizza1_Hek6UFiPN?updatedAt=1758276411591",
    alt: "pizza2",
    name: "Hawaiian ",
    desc: "Pizza sauce, mozzarella, ham, pineapple",
    price: "$9.99",
  },
];
