export const ProductsData = [
  {
    id: 1,
    img: "https://ik.imagekit.io/aswathy/images/pizza1_Hek6UFiPN?updatedAt=1758276411591",
    alt: "pizza1",
    name: "Hawaiian",
    desc: "Pizza sauce, mozzarella, ham, and sweet pineapple chunks that balance savory and tropical flavors perfectly.",
    originalPrice: "$12.99",
    price: "$9.99",
    offer: "Buy 1 Get 1 Free",
    addons: [
      { id: "ketchup", name: "Ketchup", price: 0.5 },
      { id: "extra-cheese", name: "Extra Cheese", price: 1.0 },
      { id: "olives", name: "Olives", price: 0.75 },
    ],
  },
  {
    id: 2,
    img: "https://ik.imagekit.io/aswathy/images/pizza1_Hek6UFiPN?updatedAt=1758276411591",
    alt: "pizza2",
    name: "Pepperoni Feast",
    desc: "Classic pizza sauce layered with mozzarella and generous slices of spicy pepperoni for a timeless favorite.",
    originalPrice: "$14.49",
    price: "$11.49",
    offer: "20% Off Today",
    addons: [
      { id: "garlic-dip", name: "Garlic Dip", price: 0.75 },
      { id: "extra-pepperoni", name: "Extra Pepperoni", price: 1.5 },
      { id: "jalapenos", name: "Jalapeños", price: 1.0 },
    ],
  },
  {
    id: 3,
    img: "https://ik.imagekit.io/aswathy/images/pizza1_Hek6UFiPN?updatedAt=1758276411591",
    alt: "pizza3",
    name: "Veggie Supreme",
    desc: "Loaded with fresh bell peppers, onions, mushrooms, black olives, and tomatoes on a mozzarella base.",
    originalPrice: "$20.99",
    price: "$10.49",
    offer: "Flat 50% Off",
    addons: [
      { id: "chili-flakes", name: "Chili Flakes", price: 0.25 },
      { id: "extra-mushrooms", name: "Extra Mushrooms", price: 1.0 },
      { id: "green-olives", name: "Green Olives", price: 0.75 },
    ],
  },
  {
    id: 4,
    img: "https://ik.imagekit.io/aswathy/images/pizza1_Hek6UFiPN?updatedAt=1758276411591",
    alt: "pizza4",
    name: "BBQ Chicken",
    desc: "Tangy BBQ sauce topped with grilled chicken, red onions, mozzarella, and a smoky finish.",
    originalPrice: "$15.99",
    price: "$12.99",
    offer: "Buy 2 Get 1 Free",
    addons: [
      { id: "bbq-sauce", name: "Extra BBQ Sauce", price: 0.75 },
      { id: "bacon", name: "Crispy Bacon", price: 1.5 },
      { id: "cheddar", name: "Cheddar Cheese", price: 1.0 },
    ],
  },
  {
    id: 5,
    img: "https://ik.imagekit.io/aswathy/images/pizza1_Hek6UFiPN?updatedAt=1758276411591",
    alt: "pizza5",
    name: "Four Cheese",
    desc: "A rich blend of mozzarella, cheddar, parmesan, and gorgonzola melted together on a golden crust.",
    originalPrice: "$13.99",
    price: "$11.99",
    offer: "Hot Deal",
    addons: [
      { id: "parmesan", name: "Grated Parmesan", price: 0.5 },
      { id: "truffle-oil", name: "Truffle Oil Drizzle", price: 1.75 },
      { id: "herbs", name: "Italian Herbs", price: 0.25 },
    ],
  },
  {
    id: 6,
    img: "https://ik.imagekit.io/aswathy/images/pizza1_Hek6UFiPN?updatedAt=1758276411591",
    alt: "pizza6",
    name: "Spicy Veg Delight",
    desc: "Pizza sauce, mozzarella, jalapeños, red chilies, and fresh veggies for those who love extra heat.",
    originalPrice: "$13.99",
    price: "$10.99",
    offer: "Hot Deal",
    addons: [
      { id: "extra-jalapenos", name: "Extra Jalapeños", price: 1.0 },
      { id: "hot-sauce", name: "Hot Sauce", price: 0.5 },
      { id: "chili-oil", name: "Chili Oil", price: 0.75 },
    ],
  },
];
